class Utils:
    urls = ['https://www.trueachievements.com/game-pass-ultimate/games', 
            "https://www.trueachievements.com/xbox-one/games", 
            "https://www.trueachievements.com/xbox-360/games", 
            "https://www.trueachievements.com/windows/games", 
            "https://www.trueachievements.com/xbox-series-x/games"]
    
    output_files = ['game_pass_games.csv',
                    'xbox_one_games.csv', 
                    'xbox_360_games.csv', 
                    'windows_games.csv',
                    'series_x_games.csv',
                    'all_games.csv']
    
    columns_list = ["Name",
                    "Base TA",
                    "Overall TA",
                    "Base GS",
                    "Overall GS",
                    "Base Ratio",
                    "Overall Ratio",
                    "Base Time",
                    "Overall Time",
                    "Min Time",
                    "Site Rating",
                    "Num Gamers",
                    "Base Num Achievements",
                    "Overall Num Achievements",
                    "Base SSD",
                    "Base TAD Rate",
                    "Overall SSD Rate",
                    "Overall TAD Rate",
                    "Developer(s)",
                    "Publisher(s)",
                    "is 360?",
                    "BCMX Value",
                    "PDU",
                    "Server Closure",
                    "Delisted",
                    "Install Size",
                    "Genres"]