Add On Achievements: []
Base Completion Time:
- 15.0
- 20.0
Base GS: 1000
Base Game Achievements:
- Achievement Name: Kill 100 Enemies
  Description: Kill 100 Enemies
  GS: '25'
  Guide: true
  Number of Gamers: 47285
  Percentage of Gamers: 84%
  Ratio: 1.08
  TA: '27'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Kill 1000 Enemies
  Description: Kill 1000 Enemies
  GS: '25'
  Guide: false
  Number of Gamers: 13190
  Percentage of Gamers: 24%
  Ratio: 2.05
  TA: '51'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Kill 10000 Enemies
  Description: Kill 10000 Enemies
  GS: '50'
  Guide: true
  Number of Gamers: 2481
  Percentage of Gamers: 4%
  Ratio: 4.74
  TA: '237'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Multi-Kill 5
  Description: Kill 5 Enemies In A Row
  GS: '25'
  Guide: true
  Number of Gamers: 21668
  Percentage of Gamers: 39%
  Ratio: 1.6
  TA: '40'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
- Achievement Name: Multi-Kill 10
  Description: Kill 10 Enemies In A Row
  GS: '50'
  Guide: true
  Number of Gamers: 5730
  Percentage of Gamers: 10%
  Ratio: 3.12
  TA: '156'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
- Achievement Name: Friendly-Fire 20
  Description: Get 20 Enemies To Kill Each Other With Friendly Fire
  GS: '25'
  Guide: true
  Number of Gamers: 9726
  Percentage of Gamers: 17%
  Ratio: 2.39
  TA: '59'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: In-Fight 100
  Description: Get 100 Enemies To Kill Each Other
  GS: '50'
  Guide: true
  Number of Gamers: 5833
  Percentage of Gamers: 10%
  Ratio: 3.09
  TA: '154'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Shield Breaker
  Description: Break 10 Shields
  GS: '25'
  Guide: true
  Number of Gamers: 9556
  Percentage of Gamers: 17%
  Ratio: 2.41
  TA: '60'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Cloak And Dagger
  Description: Kill 10 Cloaked Enemies
  GS: '25'
  Guide: true
  Number of Gamers: 6404
  Percentage of Gamers: 11%
  Ratio: 2.95
  TA: '73'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Splatter Master
  Description: Obliterate 100 Enemies
  GS: '50'
  Guide: true
  Number of Gamers: 22303
  Percentage of Gamers: 40%
  Ratio: 1.58
  TA: '79'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Corrosive
  Description: Melt 20 Enemies With The Chaos Caster
  GS: '25'
  Guide: true
  Number of Gamers: 4728
  Percentage of Gamers: 8%
  Ratio: 3.43
  TA: '85'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
  - Cumulative +
- Achievement Name: Pacifist
  Description: Finish A Level Without Killing Any Enemies
  GS: '50'
  Guide: true
  Number of Gamers: 2471
  Percentage of Gamers: 4%
  Ratio: 4.75
  TA: '237'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Watch Your Step
  Description: Kill 20 Enemies With Environmental Hazards
  GS: '25'
  Guide: true
  Number of Gamers: 26059
  Percentage of Gamers: 47%
  Ratio: 1.46
  TA: '36'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
- Achievement Name: Little Spender
  Description: Make 1 Purchase
  GS: '10'
  Guide: true
  Number of Gamers: 19781
  Percentage of Gamers: 35%
  Ratio: 1.68
  TA: '16'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Big Spender
  Description: Make 5 Purchases
  GS: '25'
  Guide: true
  Number of Gamers: 4473
  Percentage of Gamers: 8%
  Ratio: 3.53
  TA: '88'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
  - Shop
- Achievement Name: Pocket Money
  Description: Pick Up 10 Ore
  GS: '10'
  Guide: false
  Number of Gamers: 26831
  Percentage of Gamers: 48%
  Ratio: 1.44
  TA: '14'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: I'm Rich
  Description: Pick Up 25 Ore
  GS: '25'
  Guide: false
  Number of Gamers: 15393
  Percentage of Gamers: 28%
  Ratio: 1.9
  TA: '47'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Imagine The Wealth
  Description: Pick Up 50 Ore
  GS: '50'
  Guide: true
  Number of Gamers: 9325
  Percentage of Gamers: 17%
  Ratio: 2.44
  TA: '122'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Fist Parade
  Description: Obliterate An Enemy With Your Fists
  GS: '25'
  Guide: true
  Number of Gamers: 23884
  Percentage of Gamers: 43%
  Ratio: 1.52
  TA: '38'
  Tags:
  - Online/Offline
  - Single Player
  - Versus
- Achievement Name: Mopping Up
  Description: Kill All Enemies In A Level
  GS: '50'
  Guide: false
  Number of Gamers: 22878
  Percentage of Gamers: 41%
  Ratio: 1.56
  TA: '78'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Hard Target
  Description: Finish A Level Without Taking Damage
  GS: '25'
  Guide: true
  Number of Gamers: 2040
  Percentage of Gamers: 4%
  Ratio: 5.23
  TA: '130'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: No Big Deal
  Description: Finish A Level Without Dying
  GS: '10'
  Guide: true
  Number of Gamers: 44838
  Percentage of Gamers: 80%
  Ratio: 1.11
  TA: '11'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Kind Of A Big Deal
  Description: Finish A Level Without Dying On Hard Difficulty
  GS: '25'
  Guide: true
  Number of Gamers: 2589
  Percentage of Gamers: 5%
  Ratio: 4.64
  TA: '116'
  Tags:
  - Offline Mode
  - Single Player
  - Difficulty Specific
- Achievement Name: A Really Big Deal
  Description: Finish A Level With 100% On Hardest Difficulty
  GS: '50'
  Guide: true
  Number of Gamers: 2036
  Percentage of Gamers: 4%
  Ratio: 5.24
  TA: '262'
  Tags:
  - Offline Mode
  - Single Player
  - Difficulty Specific
- Achievement Name: Getting By
  Description: Finish 10 Levels
  GS: '10'
  Guide: true
  Number of Gamers: 13403
  Percentage of Gamers: 24%
  Ratio: 2.04
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Completionist
  Description: Finish A Level With 100% On Any Difficulty
  GS: '25'
  Guide: false
  Number of Gamers: 5040
  Percentage of Gamers: 9%
  Ratio: 3.32
  TA: '83'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Hidden Exit
  Description: Find A Hidden Exit In A Level
  GS: '10'
  Guide: true
  Number of Gamers: 3427
  Percentage of Gamers: 6%
  Ratio: 4.03
  TA: '40'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Explorer
  Description: Find All The Secrets In A Level
  GS: '25'
  Guide: true
  Number of Gamers: 6564
  Percentage of Gamers: 12%
  Ratio: 2.91
  TA: '72'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: It's Finally Over
  Description: Finish The Campaign
  GS: '75'
  Guide: false
  Number of Gamers: 6613
  Percentage of Gamers: 12%
  Ratio: 2.9
  TA: '218'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
  - Story Completed
- Achievement Name: Go Get Some Fresh Air
  Description: Finish The Campaign With 100% On All Levels
  GS: '100'
  Guide: true
  Number of Gamers: 1226
  Percentage of Gamers: 2%
  Ratio: 6.75
  TA: '675'
  Tags:
  - Offline Game Mode
  - Single Player
Base Ratio: 3.324
Base TA: 3324
Delisted: false
Developer: Bounding Box Software
Game Name: Prodeus
Genres: First Person Shooter, Action Horror
Install Size: 1960.0
Number of Completions: 1163
Number of Gamers: 55973
Overall Completion Time:
- 15.0
- 20.0
Overall GS: 1000
Overall Ratio: 3.324
Overall TA: 3324
PDU: 0
Percentage Completed: 2.08
Publisher: Humble Games
Release Date: 23 September 2022
Server Closure: false
Site Rating: 3.98
Update Achievements: []
Walkthrough: false
