Add On Achievements: []
Base Completion Time:
- 20.0
- 25.0
Base GS: 1000
Base Game Achievements:
- Achievement Name: The old man's proud
  Description: You've completed Cleanvillle
  GS: '15'
  Guide: false
  Number of Gamers: 1713
  Percentage of Gamers: 77%
  Ratio: 1.14
  TA: '17'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: On the swamp
  Description: "You\u2019ve completed Mudborough"
  GS: '15'
  Guide: false
  Number of Gamers: 1416
  Percentage of Gamers: 63%
  Ratio: 1.25
  TA: '18'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Pumped it out
  Description: You've completed Gemtown
  GS: '15'
  Guide: false
  Number of Gamers: 1251
  Percentage of Gamers: 56%
  Ratio: 1.33
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: I'm the best at the playground
  Description: You've completed Enville
  GS: '15'
  Guide: false
  Number of Gamers: 1143
  Percentage of Gamers: 51%
  Ratio: 1.39
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: "The blueprint on the wall\u2026"
  Description: "You\u2019ve completed Catrough"
  GS: '15'
  Guide: false
  Number of Gamers: 1048
  Percentage of Gamers: 47%
  Ratio: 1.45
  TA: '21'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Hooligans
  Description: You've completed Philville
  GS: '15'
  Guide: false
  Number of Gamers: 976
  Percentage of Gamers: 44%
  Ratio: 1.51
  TA: '22'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Radiation expert
  Description: You've completed Railtown
  GS: '15'
  Guide: false
  Number of Gamers: 948
  Percentage of Gamers: 42%
  Ratio: 1.53
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: "Light at the end of the tunnel\u2026"
  Description: "You\u2019ve completed Highland Tunnel"
  GS: '15'
  Guide: false
  Number of Gamers: 923
  Percentage of Gamers: 41%
  Ratio: 1.55
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: The mouse ran up the clock...
  Description: You've completed Farmley
  GS: '15'
  Guide: false
  Number of Gamers: 857
  Percentage of Gamers: 38%
  Ratio: 1.61
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Turntable mechanic
  Description: You've completed Playford Hills
  GS: '15'
  Guide: false
  Number of Gamers: 816
  Percentage of Gamers: 37%
  Ratio: 1.65
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: It's a small step for a Renovator...
  Description: You picked up your first trash
  GS: '15'
  Guide: true
  Number of Gamers: 2231
  Percentage of Gamers: 100%
  Ratio: 1.0
  TA: '15'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Senior Renovator
  Description: You picked up 1000 small trash
  GS: '15'
  Guide: false
  Number of Gamers: 968
  Percentage of Gamers: 43%
  Ratio: 1.51
  TA: '22'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Segregation expert
  Description: 200 items were correctly thrown into a segregated container
  GS: '15'
  Guide: true
  Number of Gamers: 657
  Percentage of Gamers: 29%
  Ratio: 1.84
  TA: '27'
  Tags:
  - Offline Mode
  - Single Player
  - Missable
- Achievement Name: '#1 pick in the draft'
  Description: 3 pointer from Renovator
  GS: '15'
  Guide: false
  Number of Gamers: 1899
  Percentage of Gamers: 85%
  Ratio: 1.08
  TA: '16'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: First star
  Description: You managed to collect the first star
  GS: '15'
  Guide: false
  Number of Gamers: 1840
  Percentage of Gamers: 82%
  Ratio: 1.1
  TA: '16'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: 10 stars award
  Description: You managed to collect 10 stars
  GS: '20'
  Guide: false
  Number of Gamers: 1365
  Percentage of Gamers: 61%
  Ratio: 1.27
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: 30 stars award
  Description: You managed to collect 30 stars
  GS: '25'
  Guide: false
  Number of Gamers: 935
  Percentage of Gamers: 42%
  Ratio: 1.54
  TA: '38'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: "I\u2019m pretty sure there is a little more!"
  Description: You managed to collect 75 stars!
  GS: '30'
  Guide: true
  Number of Gamers: 538
  Percentage of Gamers: 24%
  Ratio: 2.03
  TA: '61'
  Tags:
  - Offline Mode
  - Single Player
  - Missable
  - Buggy
- Achievement Name: "80 stars? Your Majesty\u2026"
  Description: You managed to collect all 80 stars
  GS: '50'
  Guide: true
  Number of Gamers: 509
  Percentage of Gamers: 23%
  Ratio: 2.09
  TA: '104'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Train mechanic
  Description: You managed to repair 30 train parts!
  GS: '15'
  Guide: true
  Number of Gamers: 1048
  Percentage of Gamers: 47%
  Ratio: 1.45
  TA: '21'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Storyteller
  Description: You managed to complete all the tasks!
  GS: '15'
  Guide: false
  Number of Gamers: 1822
  Percentage of Gamers: 82%
  Ratio: 1.1
  TA: '16'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Infinite power!
  Description: Congratulations you managed to upgrade all tools!
  GS: '20'
  Guide: true
  Number of Gamers: 655
  Percentage of Gamers: 29%
  Ratio: 1.84
  TA: '36'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: I like trains
  Description: You created your first train on the model
  GS: '5'
  Guide: true
  Number of Gamers: 730
  Percentage of Gamers: 33%
  Ratio: 1.75
  TA: '8'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: GET OVER HERE
  Description: Nice try Renovator! Now come back to the station!
  GS: '10'
  Guide: true
  Number of Gamers: 979
  Percentage of Gamers: 44%
  Ratio: 1.51
  TA: '15'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Getting started
  Description: You've completed Tutorial
  GS: '10'
  Guide: false
  Number of Gamers: 1985
  Percentage of Gamers: 89%
  Ratio: 1.06
  TA: '10'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Wait... what? There are tool upgrades?
  Description: Complete the game without upgrades
  GS: '25'
  Guide: true
  Number of Gamers: 470
  Percentage of Gamers: 21%
  Ratio: 2.17
  TA: '54'
  Tags:
  - Offline Mode
  - Single Player
  - Missable
- Achievement Name: You can actually take a ride????
  Description: "You\u2019ve completed Rocky Hills Resort"
  GS: '15'
  Guide: false
  Number of Gamers: 798
  Percentage of Gamers: 36%
  Ratio: 1.67
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: It was all flooded
  Description: You've completed Carlsea
  GS: '15'
  Guide: false
  Number of Gamers: 764
  Percentage of Gamers: 34%
  Ratio: 1.7
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Snowman's buddy
  Description: You've completed Oakdown
  GS: '15'
  Guide: false
  Number of Gamers: 745
  Percentage of Gamers: 33%
  Ratio: 1.73
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Renovation of the underground? Sounds cool!
  Description: "You\u2019ve completed Yellow Street Underground"
  GS: '15'
  Guide: false
  Number of Gamers: 731
  Percentage of Gamers: 33%
  Ratio: 1.74
  TA: '26'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Godlike Renovator
  Description: You've completed Limingham
  GS: '15'
  Guide: false
  Number of Gamers: 694
  Percentage of Gamers: 31%
  Ratio: 1.79
  TA: '26'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Master of Cleanville
  Description: "You\u2019ve completed Cleanville with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 1234
  Percentage of Gamers: 55%
  Ratio: 1.34
  TA: '33'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Mudborough
  Description: "You\u2019ve completed Mudborough with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 1010
  Percentage of Gamers: 45%
  Ratio: 1.48
  TA: '37'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Gemtown
  Description: "You\u2019ve completed Gemtown with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 1044
  Percentage of Gamers: 47%
  Ratio: 1.46
  TA: '36'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Enville
  Description: "You\u2019ve completed Enville with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 915
  Percentage of Gamers: 41%
  Ratio: 1.56
  TA: '39'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Catrough
  Description: "You\u2019ve completed Catrough with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 841
  Percentage of Gamers: 38%
  Ratio: 1.63
  TA: '40'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Philville
  Description: "You\u2019ve completed Philville with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 819
  Percentage of Gamers: 37%
  Ratio: 1.65
  TA: '41'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Railtown
  Description: "You\u2019ve completed Railtown with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 834
  Percentage of Gamers: 37%
  Ratio: 1.63
  TA: '40'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Highland Tunnel
  Description: "You\u2019ve completed Highland tunnel with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 816
  Percentage of Gamers: 37%
  Ratio: 1.65
  TA: '41'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Farmley
  Description: "You\u2019ve completed Farmley with 100% progress"
  GS: '25'
  Guide: true
  Number of Gamers: 660
  Percentage of Gamers: 30%
  Ratio: 1.84
  TA: '46'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Playford Hills
  Description: "You\u2019ve completed Playford Hills with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 709
  Percentage of Gamers: 32%
  Ratio: 1.77
  TA: '44'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Rocky Hills Resort
  Description: "You\u2019ve completed Rocky Hills Resort with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 721
  Percentage of Gamers: 32%
  Ratio: 1.76
  TA: '44'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Carlsea
  Description: "You\u2019ve completed Carlsea with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 657
  Percentage of Gamers: 29%
  Ratio: 1.84
  TA: '46'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Oakdown
  Description: "You\u2019ve completed Oakdown with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 649
  Percentage of Gamers: 29%
  Ratio: 1.85
  TA: '46'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Yellow Street Underground
  Description: "You\u2019ve completed Yellow Street Underground with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 619
  Percentage of Gamers: 28%
  Ratio: 1.89
  TA: '47'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Master of Limingham
  Description: "You\u2019ve completed Limingham with 100% progress"
  GS: '25'
  Guide: false
  Number of Gamers: 641
  Percentage of Gamers: 29%
  Ratio: 1.86
  TA: '46'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Mr Sandbox
  Description: You managed to collect 25 stars and unlocked Sandbox Mode!
  GS: '10'
  Guide: false
  Number of Gamers: 981
  Percentage of Gamers: 44%
  Ratio: 1.5
  TA: '15'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: That looks cool!
  Description: You painted your first wall
  GS: '5'
  Guide: true
  Number of Gamers: 2010
  Percentage of Gamers: 90%
  Ratio: 1.05
  TA: '5'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: This floor looks different!
  Description: You changed floor material for the first time
  GS: '5'
  Guide: true
  Number of Gamers: 1007
  Percentage of Gamers: 45%
  Ratio: 1.48
  TA: '7'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: "I wonder if I\u2026 Oh my!"
  Description: You changed material on the ceiling
  GS: '5'
  Guide: true
  Number of Gamers: 882
  Percentage of Gamers: 39%
  Ratio: 1.59
  TA: '7'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: "I\u2019ll paint one train myself for fun!"
  Description: You painted your first train
  GS: '5'
  Guide: true
  Number of Gamers: 690
  Percentage of Gamers: 31%
  Ratio: 1.8
  TA: '9'
  Tags:
  - Offline Mode
  - Single Player
  - Missable
- Achievement Name: Segregation is my passion
  Description: 400 items were correctly thrown into a segregated container
  GS: '20'
  Guide: true
  Number of Gamers: 400
  Percentage of Gamers: 18%
  Ratio: 2.36
  TA: '47'
  Tags:
  - Offline Mode
  - Single Player
  - Missable
- Achievement Name: The Boss
  Description: "You\u2019ve $200.000 on your account"
  GS: '40'
  Guide: false
  Number of Gamers: 934
  Percentage of Gamers: 42%
  Ratio: 1.54
  TA: '61'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative
- Achievement Name: Having fun?
  Description: You threw the pump in the designated place with maximum force
  GS: '10'
  Guide: true
  Number of Gamers: 651
  Percentage of Gamers: 29%
  Ratio: 1.85
  TA: '18'
  Tags:
  - Offline Mode
  - Single Player
  - Missable
Base Ratio: 1.618
Base TA: 1618
Delisted: false
Developer: Live Motion Games, ConsoleWay
Game Name: Train Station Renovation
Genres: Simulation
Install Size: 7910.0
Number of Completions: 337
Number of Gamers: 2233
Overall Completion Time:
- 20.0
- 25.0
Overall GS: 1000
Overall Ratio: 1.618
Overall TA: 1618
PDU: 0
Percentage Completed: 15.09
Publisher: Ultimate Games
Release Date: 02 June 2021
Server Closure: false
Site Rating: 3.55
Update Achievements: []
Walkthrough: false
