Add On Achievements: []
Base Completion Time:
- 113
- 114
Base GS: 1000
Base Game Achievements:
- Achievement Name: Engineer's License
  Description: Complete all tutorial scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 448
  Percentage of Gamers: 70%
  Ratio: 1.19
  TA: '17'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: New Wheels
  Description: Purchase a new locomotive in a career
  GS: '15'
  Guide: false
  Number of Gamers: 334
  Percentage of Gamers: 52%
  Ratio: 1.38
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: City Regular
  Description: Upgrade a city to level 2
  GS: '15'
  Guide: false
  Number of Gamers: 111
  Percentage of Gamers: 17%
  Ratio: 2.4
  TA: '36'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Urban Planner
  Description: Upgrade a city to level 3
  GS: '15'
  Guide: false
  Number of Gamers: 56
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '50'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: First Upgrade
  Description: Buy and equip a new locomotive part
  GS: '10'
  Guide: false
  Number of Gamers: 302
  Percentage of Gamers: 47%
  Ratio: 1.45
  TA: '14'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Kitted Out
  Description: Fully upgrade a locomotive with new parts
  GS: '15'
  Guide: false
  Number of Gamers: 234
  Percentage of Gamers: 37%
  Ratio: 1.64
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Ding!
  Description: Level up once in a career
  GS: '15'
  Guide: false
  Number of Gamers: 473
  Percentage of Gamers: 74%
  Ratio: 1.16
  TA: '17'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Lazy Sunday
  Description: Hire an Employee Driver in a career
  GS: '15'
  Guide: false
  Number of Gamers: 342
  Percentage of Gamers: 53%
  Ratio: 1.36
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Train Gang
  Description: Have 10 Employee Drivers hired and on a task at once in a career
  GS: '20'
  Guide: false
  Number of Gamers: 44
  Percentage of Gamers: 7%
  Ratio: 3.83
  TA: '76'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Pocket Change
  Description: Earn a total of one million in cash in a single career
  GS: '20'
  Guide: false
  Number of Gamers: 209
  Percentage of Gamers: 33%
  Ratio: 1.74
  TA: '34'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Locomotive Magnate
  Description: Earn a total of ten million in cash in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 54
  Percentage of Gamers: 8%
  Ratio: 3.42
  TA: '102'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Center of Attention
  Description: Level up all cities in the central region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '227'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Southern Hospitality
  Description: Level up all cities in the Southern region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 2%
  Ratio: 6.97
  TA: '209'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Slavic Power
  Description: Level up all cities in the Eastern region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.26
  TA: '217'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Wild West
  Description: Level up all cities in the Western region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.26
  TA: '217'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The King in the North
  Description: Level up all cities in the Northern region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.26
  TA: '217'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Renowned Tourist
  Description: Unlock all stations in a single career
  GS: '75'
  Guide: false
  Number of Gamers: 24
  Percentage of Gamers: 4%
  Ratio: 5.13
  TA: '385'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: World Domination
  Description: Level up all cities to level 3 in a single career
  GS: '75'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '568'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Play Smarter, Not Harder
  Description: Deliver to a city that has an active delivery bonus for what you're
    delivering (career only)
  GS: '15'
  Guide: false
  Number of Gamers: 56
  Percentage of Gamers: 9%
  Ratio: 3.42
  TA: '51'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: A Fine Addition
  Description: Own a total of 25 non-default locomotive parts
  GS: '15'
  Guide: false
  Number of Gamers: 54
  Percentage of Gamers: 8%
  Ratio: 3.42
  TA: '51'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative
- Achievement Name: Show Me the Goods
  Description: Deliver a total of 1500 cargo wagons in a single career as a company
  GS: '30'
  Guide: false
  Number of Gamers: 21
  Percentage of Gamers: 3%
  Ratio: 5.49
  TA: '164'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Commuter
  Description: Deliver a total of 3000 units of passengers and postage in a single
    career as a company
  GS: '30'
  Guide: false
  Number of Gamers: 58
  Percentage of Gamers: 9%
  Ratio: 3.3
  TA: '99'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Vice President
  Description: Level an Employee Driver to level 25 in a career
  GS: '15'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 4%
  Ratio: 5.24
  TA: '78'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The A-Team
  Description: Have 3 Employees at level 25 in a single career
  GS: '15'
  Guide: false
  Number of Gamers: 16
  Percentage of Gamers: 2%
  Ratio: 6.28
  TA: '94'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Junior
  Description: Level up to Junior rank
  GS: '15'
  Guide: false
  Number of Gamers: 253
  Percentage of Gamers: 40%
  Ratio: 1.58
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Mid-level
  Description: Level up to the Mid-level rank
  GS: '15'
  Guide: false
  Number of Gamers: 184
  Percentage of Gamers: 29%
  Ratio: 1.85
  TA: '27'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Senior
  Description: Level up to the Senior rank
  GS: '15'
  Guide: false
  Number of Gamers: 114
  Percentage of Gamers: 18%
  Ratio: 2.37
  TA: '35'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Principal
  Description: Level up to the Principal rank
  GS: '30'
  Guide: false
  Number of Gamers: 80
  Percentage of Gamers: 12%
  Ratio: 2.83
  TA: '84'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Master
  Description: Level up to the Master rank
  GS: '30'
  Guide: false
  Number of Gamers: 63
  Percentage of Gamers: 10%
  Ratio: 3.16
  TA: '95'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Railway Aficionado
  Description: Reach level 30
  GS: '75'
  Guide: false
  Number of Gamers: 40
  Percentage of Gamers: 6%
  Ratio: 4.02
  TA: '302'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Speed Demon
  Description: Complete a cargo contract with a time bonus of greater than 1.5x (career
    only)
  GS: '15'
  Guide: false
  Number of Gamers: 268
  Percentage of Gamers: 42%
  Ratio: 1.53
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Time/Date
- Achievement Name: Luxury Goods
  Description: Deliver at least 1 wagon of a Tier 3 good in a career
  GS: '15'
  Guide: false
  Number of Gamers: 82
  Percentage of Gamers: 13%
  Ratio: 2.81
  TA: '42'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Whale
  Description: Earn at least 15000 XP from a single contract or delivery
  GS: '15'
  Guide: false
  Number of Gamers: 63
  Percentage of Gamers: 10%
  Ratio: 3.22
  TA: '48'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Sunday Driver
  Description: Drive from a station to a station in a different city without being
    fined (career or scenario)
  GS: '20'
  Guide: false
  Number of Gamers: 500
  Percentage of Gamers: 78%
  Ratio: 1.12
  TA: '22'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Above the Limit
  Description: Complete a non-tutorial scenario faster than the estimated time
  GS: '15'
  Guide: false
  Number of Gamers: 64
  Percentage of Gamers: 10%
  Ratio: 3.14
  TA: '47'
  Tags:
  - Offline Mode
  - Single Player
  - Time/Date
- Achievement Name: Early Bird
  Description: Complete all non-tutorial scenarios faster than the estimated time
  GS: '75'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 1%
  Ratio: 9.5
  TA: '713'
  Tags:
  - Offline Mode
  - Single Player
  - Time/Date
- Achievement Name: Puzzle Master
  Description: Complete all Shunting scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 20
  Percentage of Gamers: 3%
  Ratio: 5.62
  TA: '84'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Unstoppable
  Description: Complete all Extreme Cargo scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 2%
  Ratio: 7.95
  TA: '119'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Steadfast
  Description: Complete all Towing scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 50
  Percentage of Gamers: 8%
  Ratio: 3.55
  TA: '53'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Massive Load
  Description: Complete a cargo contract of more than 8 wagons in a career or scenario
  GS: '15'
  Guide: false
  Number of Gamers: 283
  Percentage of Gamers: 44%
  Ratio: 1.5
  TA: '22'
  Tags:
  - Offline Game Mode
  - Single Player
Base Ratio: 4.726
Base TA: 4726
Delisted: false
Developer: Simteract
Game Name: 'Train Life: A Railway Simulator'
Genres: Simulation, Management
Install Size: 20030.0
Number of Completions: 6
Number of Gamers: 640
Overall Completion Time:
- 113
- 114
Overall GS: 1000
Overall Ratio: 4.726
Overall TA: 4726
PDU: 0
Percentage Completed: 0.94
Publisher: Nacon
Release Date: 22 September 2022
Server Closure: false
Site Rating: 3.31
Update Achievements: []
Walkthrough: false
