Add On Achievements: []
Base Completion Time:
- 92
- 93
Base GS: 1000
Base Game Achievements:
- Achievement Name: Complete your first campaign game
  Description: Complete your first campaign game
  GS: '25'
  Guide: true
  Number of Gamers: 26
  Percentage of Gamers: 28%
  Ratio: 1.87
  TA: '46'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Build four train tracks in your station
  Description: Build four train tracks in your station
  GS: '25'
  Guide: true
  Number of Gamers: 60
  Percentage of Gamers: 65%
  Ratio: 1.23
  TA: '30'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Send 1.500 passengers to their destination
  Description: Send 1.500 passengers to their destination
  GS: '25'
  Guide: false
  Number of Gamers: 50
  Percentage of Gamers: 54%
  Ratio: 1.34
  TA: '33'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Enable all bus transfer connections
  Description: Enable all bus transfer connections
  GS: '25'
  Guide: false
  Number of Gamers: 73
  Percentage of Gamers: 79%
  Ratio: 1.11
  TA: '27'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Gain 1.000.000 from ticket sales
  Description: Gain 1.000.000 from ticket sales
  GS: '25'
  Guide: false
  Number of Gamers: 39
  Percentage of Gamers: 42%
  Ratio: 1.52
  TA: '38'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Reach 1990 era in Endless Mode 1
  Description: Reach 1990 era in Endless Mode 1
  GS: '25'
  Guide: true
  Number of Gamers: 17
  Percentage of Gamers: 18%
  Ratio: 2.31
  TA: '57'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Build an advanced track playing Endless Mode
  Description: Build an advanced track playing Endless Mode 1
  GS: '25'
  Guide: false
  Number of Gamers: 44
  Percentage of Gamers: 48%
  Ratio: 1.43
  TA: '35'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Send 5.000 passengers to their destination
  Description: Send 5.000 passengers to their destination
  GS: '25'
  Guide: false
  Number of Gamers: 25
  Percentage of Gamers: 27%
  Ratio: 1.9
  TA: '47'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Arrest 250 vandals in your station
  Description: Arrest 250 vandals in your station
  GS: '25'
  Guide: true
  Number of Gamers: 10
  Percentage of Gamers: 11%
  Ratio: 3.01
  TA: '75'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Gain 500.000 from vending machine sales
  Description: Gain 500.000 from vending machine sales
  GS: '25'
  Guide: true
  Number of Gamers: 45
  Percentage of Gamers: 49%
  Ratio: 1.42
  TA: '35'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Welcome 5.000 passengers and enable all publ
  Description: Welcome 5.000 passengers and enable all public transportation
  GS: '25'
  Guide: true
  Number of Gamers: 30
  Percentage of Gamers: 33%
  Ratio: 1.74
  TA: '43'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Build an electric track playing Endless Mode
  Description: Build an electric track playing Endless Mode 1
  GS: '25'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 16%
  Ratio: 2.46
  TA: '61'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Send 25.000 passengers to their destination
  Description: Send 25.000 passengers to their destination
  GS: '25'
  Guide: true
  Number of Gamers: 9
  Percentage of Gamers: 10%
  Ratio: 3.17
  TA: '79'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Welcome 15.000 passengers by public transpor
  Description: Welcome 15.000 passengers by public transportation
  GS: '25'
  Guide: true
  Number of Gamers: 17
  Percentage of Gamers: 18%
  Ratio: 2.31
  TA: '57'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Offer some available services to your passen
  Description: Offer some available services to your passengers in Endless Mode 1
    after 2010
  GS: '25'
  Guide: true
  Number of Gamers: 19
  Percentage of Gamers: 21%
  Ratio: 2.18
  TA: '54'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Build two hyper light track playing Endless
  Description: Build two hyper light track playing Endless Mode 1 game
  GS: '25'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 14%
  Ratio: 2.75
  TA: '68'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete a game campaign
  Description: Complete a game campaign
  GS: '25'
  Guide: true
  Number of Gamers: 28
  Percentage of Gamers: 30%
  Ratio: 1.8
  TA: '45'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Complete any missions in the game
  Description: Complete any missions in the game
  GS: '25'
  Guide: true
  Number of Gamers: 18
  Percentage of Gamers: 20%
  Ratio: 2.24
  TA: '56'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Gain 15.000.000, operate all 8 train tracks
  Description: Gain 15.000.000, operate all 8 train tracks with all statistics 5 stared
  GS: '40'
  Guide: true
  Number of Gamers: 10
  Percentage of Gamers: 11%
  Ratio: 3.01
  TA: '120'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
  - Buggy
- Achievement Name: Gain 35.000.000, in any campaign modes
  Description: Gain 35.000.000, in any campaign modes
  GS: '50'
  Guide: true
  Number of Gamers: 9
  Percentage of Gamers: 10%
  Ratio: 3.17
  TA: '158'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
  - Buggy
- Achievement Name: Complete "Ready mode 1/8"
  Description: Complete "Ready mode 1/8"
  GS: '30'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 21%
  Ratio: 2.18
  TA: '65'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 2/8"
  Description: Complete "Ready mode 2/8"
  GS: '30'
  Guide: true
  Number of Gamers: 18
  Percentage of Gamers: 20%
  Ratio: 2.24
  TA: '67'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 3/8"
  Description: Complete "Ready mode 3/8"
  GS: '30'
  Guide: true
  Number of Gamers: 19
  Percentage of Gamers: 21%
  Ratio: 2.18
  TA: '65'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 4/8"
  Description: Complete "Ready mode 4/8"
  GS: '30'
  Guide: false
  Number of Gamers: 16
  Percentage of Gamers: 17%
  Ratio: 2.38
  TA: '71'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 5/8"
  Description: Complete "Ready mode 5/8"
  GS: '30'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 16%
  Ratio: 2.46
  TA: '73'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 6/8"
  Description: Complete "Ready mode 6/8"
  GS: '50'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 16%
  Ratio: 2.46
  TA: '123'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 7/8"
  Description: Complete "Ready mode 7/8"
  GS: '50'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 16%
  Ratio: 2.46
  TA: '123'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Complete "Ready mode 8/8"
  Description: Complete "Ready mode 8/8"
  GS: '50'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 16%
  Ratio: 2.46
  TA: '123'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Rebuild a struggling station in 60 days from
  Description: Rebuild a struggling station in 60 days from 1970 to 2010
  GS: '30'
  Guide: false
  Number of Gamers: 17
  Percentage of Gamers: 18%
  Ratio: 2.31
  TA: '69'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Rebuild a bankrupt station in 15 days in 197
  Description: Rebuild a bankrupt station in 15 days in 1970
  GS: '30'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 21%
  Ratio: 2.18
  TA: '65'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Rebuild an abandoned station in 15 days in 1
  Description: Rebuild an abandoned station in 15 days in 1990
  GS: '50'
  Guide: false
  Number of Gamers: 18
  Percentage of Gamers: 20%
  Ratio: 2.24
  TA: '112'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Save a crime infested station in 15 days in
  Description: Save a crime infested station in 15 days in 2010
  GS: '50'
  Guide: true
  Number of Gamers: 18
  Percentage of Gamers: 20%
  Ratio: 2.24
  TA: '112'
  Tags:
  - Offline Game Mode
  - Single Player
Base Ratio: 2.232
Base TA: 2232
Delisted: true
Developer: Appliks Apps Studio
Game Name: Train Station Simulator
Genres: Simulation
Install Size: 213.0
Number of Completions: 9
Number of Gamers: 92
Overall Completion Time:
- 92
- 93
Overall GS: 1000
Overall Ratio: 2.232
Overall TA: 2232
PDU: 0
Percentage Completed: 9.78
Publisher: Appliks Apps Studio
Release Date: 02 April 2021
Server Closure: false
Site Rating: 2.0
Update Achievements: []
Walkthrough: false
