Add On Achievements: []
Base Completion Time:
- 468
- 469
Base GS: 1000
Base Game Achievements:
- Achievement Name: Centurion
  Description: Travelled 100 miles in any locomotive
  GS: '25'
  Guide: false
  Number of Gamers: 27
  Percentage of Gamers: 37%
  Ratio: 1.64
  TA: '41'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Mega Train
  Description: Travelled 1,000 miles in any locomotive
  GS: '50'
  Guide: false
  Number of Gamers: 14
  Percentage of Gamers: 19%
  Ratio: 2.28
  TA: '114'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Unstoppable
  Description: Travelled 10,000 miles in any locomotive
  GS: '200'
  Guide: true
  Number of Gamers: 11
  Percentage of Gamers: 15%
  Ratio: 2.57
  TA: '515'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
  - Time Consuming
- Achievement Name: Trailblazer
  Description: Travelled 1 mile on foot
  GS: '10'
  Guide: true
  Number of Gamers: 61
  Percentage of Gamers: 84%
  Ratio: 1.09
  TA: '10'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Pilgrimage
  Description: Travelled 100 miles on foot
  GS: '25'
  Guide: false
  Number of Gamers: 17
  Percentage of Gamers: 23%
  Ratio: 2.07
  TA: '51'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Exodus
  Description: Travelled 1000 miles on foot
  GS: '100'
  Guide: true
  Number of Gamers: 12
  Percentage of Gamers: 16%
  Ratio: 2.46
  TA: '246'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
  - Time Consuming
- Achievement Name: Going the Distance
  Description: Completed a full service
  GS: '20'
  Guide: false
  Number of Gamers: 35
  Percentage of Gamers: 48%
  Ratio: 1.44
  TA: '28'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Gas Guzzler
  Description: Refuel 100 times
  GS: '20'
  Guide: true
  Number of Gamers: 24
  Percentage of Gamers: 33%
  Ratio: 1.74
  TA: '34'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Switcher
  Description: Changed a track switch
  GS: '5'
  Guide: true
  Number of Gamers: 71
  Percentage of Gamers: 97%
  Ratio: 1.01
  TA: '5'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Switch It Up
  Description: Changed 500 track switches
  GS: '20'
  Guide: true
  Number of Gamers: 36
  Percentage of Gamers: 49%
  Ratio: 1.42
  TA: '28'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Hinge Breaker
  Description: Used 1,000 doors
  GS: '25'
  Guide: true
  Number of Gamers: 37
  Percentage of Gamers: 51%
  Ratio: 1.4
  TA: '35'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Ventilator
  Description: Used 1,000 windows
  GS: '25'
  Guide: true
  Number of Gamers: 38
  Percentage of Gamers: 52%
  Ratio: 1.38
  TA: '34'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Connoisseur
  Description: Collected all collectables on a route
  GS: '200'
  Guide: true
  Number of Gamers: 16
  Percentage of Gamers: 22%
  Ratio: 2.13
  TA: '427'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
  - Buggy
- Achievement Name: Making Connections
  Description: Coupled to your first wagon
  GS: '5'
  Guide: false
  Number of Gamers: 51
  Percentage of Gamers: 70%
  Ratio: 1.19
  TA: '5'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Powerhaul Prep
  Description: Coupled to 1,000 cars
  GS: '50'
  Guide: true
  Number of Gamers: 20
  Percentage of Gamers: 27%
  Ratio: 1.91
  TA: '95'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Casey Jones
  Description: Attained Driver Level 20
  GS: '20'
  Guide: true
  Number of Gamers: 18
  Percentage of Gamers: 25%
  Ratio: 2.01
  TA: '40'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Workaholic
  Description: Completed 100 full services on any route
  GS: '200'
  Guide: true
  Number of Gamers: 17
  Percentage of Gamers: 23%
  Ratio: 2.07
  TA: '414'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
  - Time Consuming
Base Ratio: 2.122
Base TA: 2122
Delisted: false
Developer: Dovetail Games
Game Name: 'Train Sim World: CSX Heavy Haul (Windows)'
Genres: Simulation
Install Size: 19820.0
Number of Completions: 11
Number of Gamers: 73
Overall Completion Time:
- 468
- 469
Overall GS: 1000
Overall Ratio: 2.122
Overall TA: 2122
PDU: 0
Percentage Completed: 15.07
Publisher: Dovetail Games
Release Date: 16 November 2017
Server Closure: false
Site Rating: 3.73
Update Achievements: []
Walkthrough: false
