Add On Achievements: []
Base Completion Time:
- 0
- 1
Base GS: 1000
Base Game Achievements:
- Achievement Name: Beginner
  Description: Earn 50 stars
  GS: '5'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 20%
  Ratio: 2.23
  TA: '11'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Stargazer
  Description: Earn 100 stars
  GS: '5'
  Guide: false
  Number of Gamers: 18
  Percentage of Gamers: 16%
  Ratio: 2.52
  TA: '12'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Astronomer
  Description: Earn 150 stars
  GS: '5'
  Guide: false
  Number of Gamers: 9
  Percentage of Gamers: 8%
  Ratio: 3.57
  TA: '17'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Achiever
  Description: Earn 200 stars
  GS: '5'
  Guide: false
  Number of Gamers: 9
  Percentage of Gamers: 8%
  Ratio: 3.57
  TA: '17'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Voyager
  Description: Earn 250 stars
  GS: '5'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '20'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Steam Age
  Description: Complete 10 levels
  GS: '5'
  Guide: false
  Number of Gamers: 27
  Percentage of Gamers: 23%
  Ratio: 2.06
  TA: '10'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Industrial Age
  Description: Complete 20 levels
  GS: '5'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 17%
  Ratio: 2.46
  TA: '12'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Electrical Age
  Description: Complete 30 levels
  GS: '5'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 10%
  Ratio: 3.23
  TA: '16'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Globalisation Age
  Description: Complete 40 levels
  GS: '10'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '33'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Space Age
  Description: Complete 50 levels
  GS: '10'
  Guide: false
  Number of Gamers: 8
  Percentage of Gamers: 7%
  Ratio: 3.79
  TA: '37'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Dealmaker
  Description: Make a train visit 8 different stations
  GS: '10'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '40'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Non-Stop
  Description: Complete any level without pausing the game
  GS: '10'
  Guide: false
  Number of Gamers: 52
  Percentage of Gamers: 45%
  Ratio: 1.48
  TA: '14'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Mega-railroad
  Description: Complete a level with 300 or more track tiles
  GS: '10'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 10%
  Ratio: 3.23
  TA: '32'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Close call!
  Description: Have two trains pass by very close to each other
  GS: '5'
  Guide: false
  Number of Gamers: 50
  Percentage of Gamers: 43%
  Ratio: 1.51
  TA: '7'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Juggler
  Description: Complete a level with 8 simultaneously running trains
  GS: '25'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '84'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Vandal
  Description: Destroy a building worth 100k
  GS: '5'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 11%
  Ratio: 2.97
  TA: '14'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Lucky vandal
  Description: Destroy a building worth 100k and complete a level
  GS: '10'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 11%
  Ratio: 2.97
  TA: '29'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Ouroboros
  Description: Make a train crash into itself
  GS: '5'
  Guide: false
  Number of Gamers: 8
  Percentage of Gamers: 7%
  Ratio: 3.79
  TA: '18'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Highlander
  Description: Finish the level with only one train working
  GS: '20'
  Guide: false
  Number of Gamers: 17
  Percentage of Gamers: 15%
  Ratio: 2.6
  TA: '52'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Full garage
  Description: Get 8 locomotives on any level
  GS: '10'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 11%
  Ratio: 2.97
  TA: '29'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Upgrade complete
  Description: Upgrade 8 or more locomotives on one level
  GS: '15'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 10%
  Ratio: 3.23
  TA: '48'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Tortoise
  Description: Get 5 stars on any level playing on normal speed only
  GS: '10'
  Guide: false
  Number of Gamers: 36
  Percentage of Gamers: 31%
  Ratio: 1.78
  TA: '17'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Hare
  Description: Complete any level with 5 stars on 2x speed only
  GS: '15'
  Guide: true
  Number of Gamers: 18
  Percentage of Gamers: 16%
  Ratio: 2.52
  TA: '37'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Hare with an espresso
  Description: Complete any level with 5 stars on 4x speed only
  GS: '25'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 13%
  Ratio: 2.76
  TA: '69'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Get out my way
  Description: Have one train crash into another from behind
  GS: '5'
  Guide: false
  Number of Gamers: 39
  Percentage of Gamers: 34%
  Ratio: 1.71
  TA: '8'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Critical care
  Description: Crash and repair one locomotive 5 times
  GS: '5'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '16'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Bridgemania
  Description: Build 5 bridges and finish the level
  GS: '5'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 11%
  Ratio: 2.97
  TA: '14'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: One way
  Description: Complete a level using a tunnel only in one direction
  GS: '10'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 17%
  Ratio: 2.46
  TA: '24'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Squander
  Description: Build a tunnel and finish the level without using it
  GS: '5'
  Guide: false
  Number of Gamers: 16
  Percentage of Gamers: 14%
  Ratio: 2.68
  TA: '13'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: To the eyeballs!
  Description: Complete the level sending only fully loaded trains
  GS: '10'
  Guide: false
  Number of Gamers: 91
  Percentage of Gamers: 79%
  Ratio: 1.12
  TA: '11'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Individual delivery
  Description: Send 3 trains in a row with only one car each
  GS: '5'
  Guide: false
  Number of Gamers: 31
  Percentage of Gamers: 27%
  Ratio: 1.92
  TA: '9'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Jewelry accuracy
  Description: Complete any level of 2-5 era without destroying any objects on the
    map
  GS: '15'
  Guide: false
  Number of Gamers: 20
  Percentage of Gamers: 17%
  Ratio: 2.39
  TA: '35'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: At the last moment!
  Description: Get 5 stars delivering the last train in the final 5 seconds. The train
    should not be stopped.
  GS: '25'
  Guide: false
  Number of Gamers: 21
  Percentage of Gamers: 18%
  Ratio: 2.34
  TA: '58'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Multilevel road
  Description: Place tracks under a bridge
  GS: '5'
  Guide: false
  Number of Gamers: 30
  Percentage of Gamers: 26%
  Ratio: 1.95
  TA: '9'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Relocation
  Description: Send a train with workers from one city to another
  GS: '5'
  Guide: false
  Number of Gamers: 28
  Percentage of Gamers: 24%
  Ratio: 2.02
  TA: '10'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Common cause
  Description: Send trains with workers from different cities to one production
  GS: '5'
  Guide: false
  Number of Gamers: 46
  Percentage of Gamers: 40%
  Ratio: 1.58
  TA: '7'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Forgot something
  Description: Return a train back to its departure station
  GS: '5'
  Guide: false
  Number of Gamers: 45
  Percentage of Gamers: 39%
  Ratio: 1.59
  TA: '7'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Without a lunch break
  Description: Complete any level having at least one resource produced the entire
    time
  GS: '10'
  Guide: false
  Number of Gamers: 24
  Percentage of Gamers: 21%
  Ratio: 2.18
  TA: '21'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Prick of conscience
  Description: Fail 10 star tasks
  GS: '5'
  Guide: false
  Number of Gamers: 14
  Percentage of Gamers: 12%
  Ratio: 2.86
  TA: '14'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Builder
  Description: Build 1000 track tiles
  GS: '5'
  Guide: false
  Number of Gamers: 31
  Percentage of Gamers: 27%
  Ratio: 1.92
  TA: '9'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Overseer
  Description: Build 5000 track tiles
  GS: '15'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 11%
  Ratio: 2.97
  TA: '44'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Engineer
  Description: Build 10000 track tiles
  GS: '20'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '67'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: BBQ
  Description: Remove 50 animals
  GS: '5'
  Guide: false
  Number of Gamers: 8
  Percentage of Gamers: 7%
  Ratio: 3.79
  TA: '18'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Woodcutter
  Description: Remove 300 trees
  GS: '5'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.57
  TA: '17'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Just in time!
  Description: Transport 500 trains
  GS: '15'
  Guide: false
  Number of Gamers: 32
  Percentage of Gamers: 28%
  Ratio: 1.89
  TA: '28'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Sabotage
  Description: Blow up 100 trains
  GS: '15'
  Guide: false
  Number of Gamers: 9
  Percentage of Gamers: 8%
  Ratio: 3.57
  TA: '53'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Missed it!
  Description: Transport 50 trains to a wrong destination
  GS: '5'
  Guide: false
  Number of Gamers: 13
  Percentage of Gamers: 11%
  Ratio: 2.97
  TA: '14'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: It's no coincidence
  Description: Go bankrupt 10 times
  GS: '10'
  Guide: false
  Number of Gamers: 8
  Percentage of Gamers: 7%
  Ratio: 3.79
  TA: '37'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Need to think
  Description: Press pause button 100 times
  GS: '5'
  Guide: false
  Number of Gamers: 65
  Percentage of Gamers: 57%
  Ratio: 1.33
  TA: '6'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Living it large
  Description: Become a millionaire
  GS: '30'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 10%
  Ratio: 3.23
  TA: '96'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Environmental activist
  Description: Remove construction equipment for 100K
  GS: '10'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '40'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Bridge builder
  Description: Build 100 bridges
  GS: '10'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '33'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Metro builder
  Description: Build 100 tunnels
  GS: '10'
  Guide: false
  Number of Gamers: 6
  Percentage of Gamers: 5%
  Ratio: 4.37
  TA: '43'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Will work
  Description: Repair 50 locomotives
  GS: '10'
  Guide: false
  Number of Gamers: 9
  Percentage of Gamers: 8%
  Ratio: 3.57
  TA: '35'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Railroad tycoon
  Description: Buy 150 locomotives
  GS: '15'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '60'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Innovator
  Description: Upgrade 200 locomotives
  GS: '15'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '50'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Miscalculation
  Description: Remove 50 bridges or tunnels
  GS: '10'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '40'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Large construction
  Description: Build productions totaling 500K
  GS: '15'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 10%
  Ratio: 3.23
  TA: '48'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Forgotten
  Description: Deliver the first train in the end of the level without stopping it
  GS: '20'
  Guide: false
  Number of Gamers: 6
  Percentage of Gamers: 5%
  Ratio: 4.37
  TA: '87'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Alchemist
  Description: Earn 300 stars
  GS: '5'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '20'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Astrophysicist
  Description: Earn 350 stars
  GS: '5'
  Guide: false
  Number of Gamers: 6
  Percentage of Gamers: 5%
  Ratio: 4.37
  TA: '21'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Red Dwarf
  Description: Earn 400 stars
  GS: '10'
  Guide: false
  Number of Gamers: 4
  Percentage of Gamers: 3%
  Ratio: 5.36
  TA: '53'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Supernova
  Description: Earn 450 stars
  GS: '10'
  Guide: false
  Number of Gamers: 1
  Percentage of Gamers: 1%
  Ratio: 10.72
  TA: '107'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Per Aspera
  Description: Complete 80 levels
  GS: '10'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '40'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Ad Astra
  Description: Complete 90 levels
  GS: '15'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 6%
  Ratio: 4.05
  TA: '60'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Tourism Age
  Description: Complete 60 levels
  GS: '10'
  Guide: false
  Number of Gamers: 4
  Percentage of Gamers: 3%
  Ratio: 5.36
  TA: '53'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Urbanization Age
  Description: Complete 70 levels
  GS: '10'
  Guide: false
  Number of Gamers: 3
  Percentage of Gamers: 3%
  Ratio: 6.19
  TA: '61'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Official Train Driver
  Description: Unlock all the other achievements
  GS: '50'
  Guide: false
  Number of Gamers: 3
  Percentage of Gamers: 3%
  Ratio: 6.19
  TA: '309'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Atomic Age
  Description: Complete 100 levels
  GS: '15'
  Guide: false
  Number of Gamers: 2
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '113'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Information Age
  Description: Complete 110 levels
  GS: '15'
  Guide: false
  Number of Gamers: 2
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '113'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Digital Age
  Description: Complete 120 levels
  GS: '40'
  Guide: false
  Number of Gamers: 3
  Percentage of Gamers: 3%
  Ratio: 6.19
  TA: '247'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Pink Ruby
  Description: Complete 50 levels
  GS: '10'
  Guide: false
  Number of Gamers: 4
  Percentage of Gamers: 3%
  Ratio: 5.36
  TA: '53'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Trapiche Emerald
  Description: Complete 100 levels
  GS: '20'
  Guide: false
  Number of Gamers: 3
  Percentage of Gamers: 3%
  Ratio: 6.19
  TA: '123'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Star Sapphire
  Description: Complete 158 levels
  GS: '40'
  Guide: false
  Number of Gamers: 3
  Percentage of Gamers: 3%
  Ratio: 6.19
  TA: '247'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Vostok
  Description: Earn 500 stars
  GS: '10'
  Guide: false
  Number of Gamers: 2
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '75'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Astrochemist
  Description: Earn 550 stars
  GS: '15'
  Guide: false
  Number of Gamers: 2
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '113'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Arcturus
  Description: Earn 600 stars
  GS: '40'
  Guide: false
  Number of Gamers: 3
  Percentage of Gamers: 3%
  Ratio: 6.19
  TA: '247'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Miner
  Description: Earn 250 gems
  GS: '10'
  Guide: false
  Number of Gamers: 4
  Percentage of Gamers: 3%
  Ratio: 5.36
  TA: '53'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Gemologist
  Description: Earn 500 gems
  GS: '20'
  Guide: false
  Number of Gamers: 2
  Percentage of Gamers: 2%
  Ratio: 7.58
  TA: '151'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Jeweller
  Description: Earn 790 gems
  GS: '40'
  Guide: false
  Number of Gamers: 5
  Percentage of Gamers: 4%
  Ratio: 4.79
  TA: '191'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
Base Ratio: 4.206
Base TA: 4206
Delisted: false
Developer: Flazm
Game Name: Train Valley 2 - Community Edition
Genres: Management
Install Size: 1460.0
Number of Completions: 1
Number of Gamers: 115
Overall Completion Time:
- 0
- 1
Overall GS: 1000
Overall Ratio: 4.206
Overall TA: 4206
PDU: 0
Percentage Completed: 0.87
Publisher: BlitWorks
Release Date: 22 November 2023
Server Closure: false
Site Rating: 3.25
Update Achievements: []
Walkthrough: false
