Add On Achievements: []
Base Completion Time:
- 113
- 114
Base GS: 1000
Base Game Achievements:
- Achievement Name: Engineer's License
  Description: Complete all tutorial scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 411
  Percentage of Gamers: 69%
  Ratio: 1.19
  TA: '17'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: New Wheels
  Description: Purchase a new locomotive in a career
  GS: '15'
  Guide: false
  Number of Gamers: 311
  Percentage of Gamers: 53%
  Ratio: 1.37
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: City Regular
  Description: Upgrade a city to level 2
  GS: '15'
  Guide: false
  Number of Gamers: 105
  Percentage of Gamers: 18%
  Ratio: 2.36
  TA: '35'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Urban Planner
  Description: Upgrade a city to level 3
  GS: '15'
  Guide: false
  Number of Gamers: 54
  Percentage of Gamers: 9%
  Ratio: 3.29
  TA: '49'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: First Upgrade
  Description: Buy and equip a new locomotive part
  GS: '10'
  Guide: false
  Number of Gamers: 287
  Percentage of Gamers: 48%
  Ratio: 1.43
  TA: '14'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Kitted Out
  Description: Fully upgrade a locomotive with new parts
  GS: '15'
  Guide: false
  Number of Gamers: 222
  Percentage of Gamers: 38%
  Ratio: 1.62
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Ding!
  Description: Level up once in a career
  GS: '15'
  Guide: false
  Number of Gamers: 438
  Percentage of Gamers: 74%
  Ratio: 1.15
  TA: '17'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Lazy Sunday
  Description: Hire an Employee Driver in a career
  GS: '15'
  Guide: false
  Number of Gamers: 317
  Percentage of Gamers: 54%
  Ratio: 1.36
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Shop
- Achievement Name: Train Gang
  Description: Have 10 Employee Drivers hired and on a task at once in a career
  GS: '20'
  Guide: false
  Number of Gamers: 43
  Percentage of Gamers: 7%
  Ratio: 3.69
  TA: '73'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Pocket Change
  Description: Earn a total of one million in cash in a single career
  GS: '20'
  Guide: false
  Number of Gamers: 194
  Percentage of Gamers: 33%
  Ratio: 1.74
  TA: '34'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Locomotive Magnate
  Description: Earn a total of ten million in cash in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 52
  Percentage of Gamers: 9%
  Ratio: 3.36
  TA: '100'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Center of Attention
  Description: Level up all cities in the central region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 2%
  Ratio: 7.31
  TA: '219'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Southern Hospitality
  Description: Level up all cities in the Southern region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.0
  TA: '210'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Slavic Power
  Description: Level up all cities in the Eastern region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.0
  TA: '210'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Wild West
  Description: Level up all cities in the Western region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.0
  TA: '210'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The King in the North
  Description: Level up all cities in the Northern region to level 3 in a single career
  GS: '30'
  Guide: false
  Number of Gamers: 12
  Percentage of Gamers: 2%
  Ratio: 7.0
  TA: '210'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Renowned Tourist
  Description: Unlock all stations in a single career
  GS: '75'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 4%
  Ratio: 5.05
  TA: '379'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: World Domination
  Description: Level up all cities to level 3 in a single career
  GS: '75'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 2%
  Ratio: 7.31
  TA: '548'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Play Smarter, Not Harder
  Description: Deliver to a city that has an active delivery bonus for what you're
    delivering (career only)
  GS: '15'
  Guide: false
  Number of Gamers: 54
  Percentage of Gamers: 9%
  Ratio: 3.29
  TA: '49'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: A Fine Addition
  Description: Own a total of 25 non-default locomotive parts
  GS: '15'
  Guide: false
  Number of Gamers: 52
  Percentage of Gamers: 9%
  Ratio: 3.36
  TA: '50'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative
- Achievement Name: Show Me the Goods
  Description: Deliver a total of 1500 cargo wagons in a single career as a company
  GS: '30'
  Guide: false
  Number of Gamers: 21
  Percentage of Gamers: 4%
  Ratio: 5.29
  TA: '158'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Commuter
  Description: Deliver a total of 3000 units of passengers and postage in a single
    career as a company
  GS: '30'
  Guide: false
  Number of Gamers: 57
  Percentage of Gamers: 10%
  Ratio: 3.21
  TA: '96'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Vice President
  Description: Level an Employee Driver to level 25 in a career
  GS: '15'
  Guide: false
  Number of Gamers: 22
  Percentage of Gamers: 4%
  Ratio: 5.16
  TA: '77'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The A-Team
  Description: Have 3 Employees at level 25 in a single career
  GS: '15'
  Guide: false
  Number of Gamers: 15
  Percentage of Gamers: 3%
  Ratio: 6.26
  TA: '93'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Junior
  Description: Level up to Junior rank
  GS: '15'
  Guide: false
  Number of Gamers: 237
  Percentage of Gamers: 40%
  Ratio: 1.57
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Mid-level
  Description: Level up to the Mid-level rank
  GS: '15'
  Guide: false
  Number of Gamers: 170
  Percentage of Gamers: 29%
  Ratio: 1.86
  TA: '27'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Senior
  Description: Level up to the Senior rank
  GS: '15'
  Guide: false
  Number of Gamers: 105
  Percentage of Gamers: 18%
  Ratio: 2.36
  TA: '35'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Principal
  Description: Level up to the Principal rank
  GS: '30'
  Guide: false
  Number of Gamers: 75
  Percentage of Gamers: 13%
  Ratio: 2.8
  TA: '84'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Master
  Description: Level up to the Master rank
  GS: '30'
  Guide: false
  Number of Gamers: 61
  Percentage of Gamers: 10%
  Ratio: 3.1
  TA: '93'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Railway Aficionado
  Description: Reach level 30
  GS: '75'
  Guide: false
  Number of Gamers: 38
  Percentage of Gamers: 6%
  Ratio: 3.93
  TA: '295'
  Tags:
  - Offline Mode
  - Single Player
  - Level
- Achievement Name: Speed Demon
  Description: Complete a cargo contract with a time bonus of greater than 1.5x (career
    only)
  GS: '15'
  Guide: false
  Number of Gamers: 250
  Percentage of Gamers: 42%
  Ratio: 1.53
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Time/Date
- Achievement Name: Luxury Goods
  Description: Deliver at least 1 wagon of a Tier 3 good in a career
  GS: '15'
  Guide: false
  Number of Gamers: 75
  Percentage of Gamers: 13%
  Ratio: 2.8
  TA: '42'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: The Whale
  Description: Earn at least 15000 XP from a single contract or delivery
  GS: '15'
  Guide: false
  Number of Gamers: 58
  Percentage of Gamers: 10%
  Ratio: 3.18
  TA: '47'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Sunday Driver
  Description: Drive from a station to a station in a different city without being
    fined (career or scenario)
  GS: '20'
  Guide: false
  Number of Gamers: 460
  Percentage of Gamers: 78%
  Ratio: 1.13
  TA: '22'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Above the Limit
  Description: Complete a non-tutorial scenario faster than the estimated time
  GS: '15'
  Guide: false
  Number of Gamers: 63
  Percentage of Gamers: 11%
  Ratio: 3.07
  TA: '46'
  Tags:
  - Offline Mode
  - Single Player
  - Time/Date
- Achievement Name: Early Bird
  Description: Complete all non-tutorial scenarios faster than the estimated time
  GS: '75'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 1%
  Ratio: 9.16
  TA: '687'
  Tags:
  - Offline Mode
  - Single Player
  - Time/Date
- Achievement Name: Puzzle Master
  Description: Complete all Shunting scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 20
  Percentage of Gamers: 3%
  Ratio: 5.42
  TA: '81'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Unstoppable
  Description: Complete all Extreme Cargo scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 10
  Percentage of Gamers: 2%
  Ratio: 7.66
  TA: '115'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Steadfast
  Description: Complete all Towing scenarios
  GS: '15'
  Guide: false
  Number of Gamers: 48
  Percentage of Gamers: 8%
  Ratio: 3.5
  TA: '52'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Massive Load
  Description: Complete a cargo contract of more than 8 wagons in a career or scenario
  GS: '15'
  Guide: false
  Number of Gamers: 265
  Percentage of Gamers: 45%
  Ratio: 1.48
  TA: '22'
  Tags:
  - Offline Game Mode
  - Single Player
Base Ratio: 4.606
Base TA: 4606
Delisted: false
Developer: Simteract
Game Name: 'Train Life: A Railway Simulator'
Genres: Simulation, Management
Install Size: 20030.0
Number of Completions: 6
Number of Gamers: 592
Overall Completion Time:
- 113
- 114
Overall GS: 1000
Overall Ratio: 4.606
Overall TA: 4606
PDU: 0
Percentage Completed: 1.01
Publisher: Nacon
Release Date: 22 September 2022
Server Closure: false
Site Rating: 3.31
Update Achievements: []
Walkthrough: false
