Add On Achievements: []
Base Completion Time:
- 20.0
- 25.0
Base GS: 1000
Base Game Achievements:
- Achievement Name: Getting started
  Description: Receive 5 stamps.
  GS: '5'
  Guide: false
  Number of Gamers: 161
  Percentage of Gamers: 58%
  Ratio: 1.31
  TA: '6'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Close call!
  Description: Get two trains pass very close to each other.
  GS: '10'
  Guide: false
  Number of Gamers: 170
  Percentage of Gamers: 61%
  Ratio: 1.27
  TA: '12'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Builder
  Description: Build 1000 track tiles.
  GS: '5'
  Guide: false
  Number of Gamers: 79
  Percentage of Gamers: 29%
  Ratio: 1.87
  TA: '9'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Prick of conscience
  Description: Fail 10 tasks.
  GS: '5'
  Guide: false
  Number of Gamers: 69
  Percentage of Gamers: 25%
  Ratio: 2.0
  TA: '10'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Living it large
  Description: Become a millionaire.
  GS: '10'
  Guide: false
  Number of Gamers: 57
  Percentage of Gamers: 21%
  Ratio: 2.2
  TA: '22'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Collector
  Description: Receive 15 stamps.
  GS: '5'
  Guide: false
  Number of Gamers: 59
  Percentage of Gamers: 21%
  Ratio: 2.16
  TA: '10'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Completely nuts!
  Description: Complete 50% of any level at speed x4.
  GS: '10'
  Guide: false
  Number of Gamers: 158
  Percentage of Gamers: 57%
  Ratio: 1.32
  TA: '13'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Need to think
  Description: Press pause button 100 times.
  GS: '5'
  Guide: true
  Number of Gamers: 137
  Percentage of Gamers: 49%
  Ratio: 1.42
  TA: '7'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Europe
  Description: Complete the first season.
  GS: '20'
  Guide: false
  Number of Gamers: 53
  Percentage of Gamers: 19%
  Ratio: 2.28
  TA: '45'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Just in time!
  Description: Transport 500 trains.
  GS: '10'
  Guide: false
  Number of Gamers: 49
  Percentage of Gamers: 18%
  Ratio: 2.37
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Madness!
  Description: Complete 80% of any level at speed x2.
  GS: '10'
  Guide: false
  Number of Gamers: 85
  Percentage of Gamers: 31%
  Ratio: 1.8
  TA: '18'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: It's no coincidence
  Description: Go bankrupt 10 times.
  GS: '5'
  Guide: false
  Number of Gamers: 47
  Percentage of Gamers: 17%
  Ratio: 2.42
  TA: '12'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Non Stop!
  Description: Complete any level on 2, 3 or 4 season without pausing the game.
  GS: '10'
  Guide: false
  Number of Gamers: 34
  Percentage of Gamers: 12%
  Ratio: 2.85
  TA: '28'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Let's roll!
  Description: Launch a rocket.
  GS: '10'
  Guide: true
  Number of Gamers: 36
  Percentage of Gamers: 13%
  Ratio: 2.77
  TA: '27'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Ouroboros
  Description: Make a train crash into itself.
  GS: '10'
  Guide: false
  Number of Gamers: 41
  Percentage of Gamers: 15%
  Ratio: 2.59
  TA: '25'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Philatelist
  Description: Receive 30 stamps.
  GS: '20'
  Guide: true
  Number of Gamers: 40
  Percentage of Gamers: 14%
  Ratio: 2.63
  TA: '52'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Foreman
  Description: Build 5000 track tiles.
  GS: '10'
  Guide: false
  Number of Gamers: 38
  Percentage of Gamers: 14%
  Ratio: 2.69
  TA: '26'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: America
  Description: Complete the second season.
  GS: '30'
  Guide: false
  Number of Gamers: 39
  Percentage of Gamers: 14%
  Ratio: 2.66
  TA: '79'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Missed it!
  Description: Transport 50 trains to a wrong destination.
  GS: '10'
  Guide: false
  Number of Gamers: 40
  Percentage of Gamers: 14%
  Ratio: 2.63
  TA: '26'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Russia
  Description: Complete the third season.
  GS: '40'
  Guide: false
  Number of Gamers: 35
  Percentage of Gamers: 13%
  Ratio: 2.81
  TA: '112'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: BBQ
  Description: Remove 50 animals.
  GS: '10'
  Guide: true
  Number of Gamers: 39
  Percentage of Gamers: 14%
  Ratio: 2.66
  TA: '26'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Sabotage
  Description: Blow up 100 trains.
  GS: '20'
  Guide: false
  Number of Gamers: 34
  Percentage of Gamers: 12%
  Ratio: 2.85
  TA: '57'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Japan
  Description: Complete the fourth season.
  GS: '60'
  Guide: false
  Number of Gamers: 29
  Percentage of Gamers: 10%
  Ratio: 3.09
  TA: '185'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Woodcutter
  Description: Remove 300 trees.
  GS: '20'
  Guide: false
  Number of Gamers: 28
  Percentage of Gamers: 10%
  Ratio: 3.14
  TA: '62'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Engineer
  Description: Build 10000 track tiles.
  GS: '30'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 8%
  Ratio: 3.47
  TA: '104'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Achtung!
  Description: Get bombed.
  GS: '10'
  Guide: true
  Number of Gamers: 30
  Percentage of Gamers: 11%
  Ratio: 3.03
  TA: '30'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
- Achievement Name: Forgotten
  Description: Complete a level with the first deployed train delivered the last.
  GS: '30'
  Guide: false
  Number of Gamers: 48
  Percentage of Gamers: 17%
  Ratio: 2.4
  TA: '72'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Tycoon
  Description: Receive 60 stamps.
  GS: '50'
  Guide: false
  Number of Gamers: 29
  Percentage of Gamers: 10%
  Ratio: 3.09
  TA: '154'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Chuck Norris
  Description: Blow up 10 trains and complete a level.
  GS: '20'
  Guide: true
  Number of Gamers: 32
  Percentage of Gamers: 12%
  Ratio: 2.94
  TA: '58'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Germany
  Description: Complete the fifth season.
  GS: '90'
  Guide: false
  Number of Gamers: 30
  Percentage of Gamers: 11%
  Ratio: 3.03
  TA: '273'
  Tags:
  - Offline Mode
  - Single Player
  - Main Storyline
  - Story Completed
- Achievement Name: Vandal
  Description: Destroy a building worth 100k.
  GS: '20'
  Guide: false
  Number of Gamers: 33
  Percentage of Gamers: 12%
  Ratio: 2.89
  TA: '57'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Lucky vandal
  Description: Destroy a building worth 100k and complete a level.
  GS: '20'
  Guide: false
  Number of Gamers: 29
  Percentage of Gamers: 10%
  Ratio: 3.09
  TA: '61'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Supercrash!
  Description: Have an accident with supertrain and complete a level.
  GS: '20'
  Guide: true
  Number of Gamers: 26
  Percentage of Gamers: 9%
  Ratio: 3.26
  TA: '65'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Peacemaker
  Description: Remove 10 tanks.
  GS: '10'
  Guide: true
  Number of Gamers: 23
  Percentage of Gamers: 8%
  Ratio: 3.47
  TA: '34'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: "\u0421hancellor"
  Description: Receive 75 stamps.
  GS: '100'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 8%
  Ratio: 3.47
  TA: '347'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: Salesman
  Description: Make a train visit 8 different stations.
  GS: '20'
  Guide: false
  Number of Gamers: 24
  Percentage of Gamers: 9%
  Ratio: 3.39
  TA: '67'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Maniac vandal
  Description: Destroy buildings worth 300k and complete a level.
  GS: '20'
  Guide: true
  Number of Gamers: 19
  Percentage of Gamers: 7%
  Ratio: 3.81
  TA: '76'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Juggler
  Description: Complete a level with 10 simultaneously running trains.
  GS: '40'
  Guide: false
  Number of Gamers: 17
  Percentage of Gamers: 6%
  Ratio: 4.03
  TA: '161'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Mega-railroad
  Description: Complete a level with 300 track tiles.
  GS: '20'
  Guide: false
  Number of Gamers: 18
  Percentage of Gamers: 6%
  Ratio: 3.92
  TA: '78'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: Official train driver
  Description: Complete all achievements.
  GS: '150'
  Guide: false
  Number of Gamers: 16
  Percentage of Gamers: 6%
  Ratio: 4.16
  TA: '624'
  Tags:
  - Offline Game Mode
  - Single Player
Base Ratio: 3.153
Base TA: 3153
Delisted: false
Developer: Flazm
Game Name: Train Valley
Genres: Management
Install Size: 637.0
Number of Completions: 16
Number of Gamers: 277
Overall Completion Time:
- 20.0
- 25.0
Overall GS: 1000
Overall Ratio: 3.153
Overall TA: 3153
PDU: 0
Percentage Completed: 5.78
Publisher: BlitWorks
Release Date: 27 July 2022
Server Closure: false
Site Rating: 2.93
Update Achievements: []
Walkthrough: false
