Add On Achievements:
- Achievement Name: 'SBD: MPXpress Yourself'
  Description: Complete the MP36 Training Module
  GS: '15'
  Guide: true
  Number of Gamers: 1409
  Percentage of Gamers: 81%
  Ratio: 1.99
  TA: '29'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'SBD: Spirit of Innovation'
  Description: Complete the F125 Training Module
  GS: '15'
  Guide: true
  Number of Gamers: 966
  Percentage of Gamers: 55%
  Ratio: 2.4
  TA: '36'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'SBD: Remote Control'
  Description: Complete the Rotem Cab Car Training Module
  GS: '15'
  Guide: false
  Number of Gamers: 987
  Percentage of Gamers: 56%
  Ratio: 2.38
  TA: '35'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: SBD:I am speed!
  Description: Complete the Race Way Scenario
  GS: '20'
  Guide: false
  Number of Gamers: 776
  Percentage of Gamers: 44%
  Ratio: 2.68
  TA: '53'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'SBD: Metrolink''s Awakening'
  Description: Complete 20 services on San Bernardino Line
  GS: '35'
  Guide: true
  Number of Gamers: 270
  Percentage of Gamers: 15%
  Ratio: 4.55
  TA: '159'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: "FTF: B\xFCcherwurm"
  Description: Complete all the training modules on Frankfurt Fulda
  GS: '15'
  Guide: true
  Number of Gamers: 711
  Percentage of Gamers: 52%
  Ratio: 2.63
  TA: '39'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'FTF: True Frankfurter'
  Description: Complete all the Scenarios on Frankfurt Fulda
  GS: '15'
  Guide: true
  Number of Gamers: 478
  Percentage of Gamers: 35%
  Ratio: 3.21
  TA: '48'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'FTF: Sweet T'
  Description: Operate the ICE-T for 100km
  GS: '10'
  Guide: true
  Number of Gamers: 1050
  Percentage of Gamers: 77%
  Ratio: 2.17
  TA: '21'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'FTF: Sailor'
  Description: Complete the Frankfurt Ferry scenario
  GS: '20'
  Guide: true
  Number of Gamers: 652
  Percentage of Gamers: 48%
  Ratio: 2.75
  TA: '55'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'FTF: Got that dog in me'
  Description: Complete all the route tasks on Frankfurt Fulda
  GS: '40'
  Guide: true
  Number of Gamers: 186
  Percentage of Gamers: 14%
  Ratio: 5.17
  TA: '206'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'EMK: About Tree Fiddy'
  Description: Complete the Class 350-1 Training Module
  GS: '15'
  Guide: false
  Number of Gamers: 1765
  Percentage of Gamers: 81%
  Ratio: 1.87
  TA: '28'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'EMK: Desiro-Boy!'
  Description: Drive the Class 350-1 for 100 miles
  GS: '10'
  Guide: true
  Number of Gamers: 1042
  Percentage of Gamers: 48%
  Ratio: 2.44
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'EMK: The Collector'
  Description: Complete the Carriage Collector scenario
  GS: '15'
  Guide: false
  Number of Gamers: 882
  Percentage of Gamers: 41%
  Ratio: 2.65
  TA: '39'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'EMK: You''ve Never Seen Anything Like It'
  Description: 'Complete all the scenarios on TSW: West Coast Mainline South'
  GS: '20'
  Guide: true
  Number of Gamers: 564
  Percentage of Gamers: 26%
  Ratio: 3.32
  TA: '66'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'EMK: Robot Rock'
  Description: Complete all the route tasks on WCML Euston - Milton Keynes
  GS: '40'
  Guide: true
  Number of Gamers: 206
  Percentage of Gamers: 9%
  Ratio: 5.5
  TA: '220'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'CJP: Passing Grade'
  Description: Complete all training modules on Cajon Pass
  GS: '20'
  Guide: false
  Number of Gamers: 125
  Percentage of Gamers: 57%
  Ratio: 3.97
  TA: '79'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'CJP: San Andreas'
  Description: Complete all scenarios on Cajon Pass
  GS: '20'
  Guide: true
  Number of Gamers: 92
  Percentage of Gamers: 42%
  Ratio: 4.63
  TA: '92'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'CJP: Taco Tuesday!'
  Description: Complete all route tasks on Cajon Pass
  GS: '20'
  Guide: false
  Number of Gamers: 46
  Percentage of Gamers: 21%
  Ratio: 6.55
  TA: '131'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'CJP: Pass Out'
  Description: Complete 10 services on Cajon Pass
  GS: '20'
  Guide: true
  Number of Gamers: 78
  Percentage of Gamers: 36%
  Ratio: 5.03
  TA: '100'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'CJP: Miles of Smiles'
  Description: Operate trains for over 100 miles on Cajon Pass
  GS: '20'
  Guide: false
  Number of Gamers: 174
  Percentage of Gamers: 80%
  Ratio: 3.36
  TA: '67'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'BOW: FortySix'
  Description: Drive the HSP46  for 46 miles within the speed limit
  GS: '20'
  Guide: false
  Number of Gamers: 48
  Percentage of Gamers: 72%
  Ratio: 4.77
  TA: '95'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'BOW: Stocking Stuffer'
  Description: Complete all the route tasks on the Boston - Worcester route
  GS: '30'
  Guide: false
  Number of Gamers: 17
  Percentage of Gamers: 25%
  Ratio: 8.02
  TA: '240'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'BOW: Top Pick'
  Description: Complete the "Draft Day" scenario
  GS: '10'
  Guide: false
  Number of Gamers: 40
  Percentage of Gamers: 60%
  Ratio: 5.23
  TA: '52'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'BOW: Worcester Wanderer'
  Description: Complete 20 services on the Boston Worcester line
  GS: '30'
  Guide: true
  Number of Gamers: 28
  Percentage of Gamers: 42%
  Ratio: 6.25
  TA: '187'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'BOW: Run Home'
  Description: Complete the "Take me Home from the Ball Game" scenario
  GS: '10'
  Guide: false
  Number of Gamers: 52
  Percentage of Gamers: 78%
  Ratio: 4.58
  TA: '45'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'PSC: Route Explorer'
  Description: Drive the Class 87/0 for 87 miles within the speed limit
  GS: '10'
  Guide: false
  Number of Gamers: 102
  Percentage of Gamers: 94%
  Ratio: 3.7
  TA: '37'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'PSC: All in the bag'
  Description: 'Complete 5 scenarios in WCML: Preston - Carlisle'
  GS: '20'
  Guide: false
  Number of Gamers: 32
  Percentage of Gamers: 29%
  Ratio: 6.6
  TA: '132'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'PSC: Coupling Up'
  Description: 'Complete 15 coupling maneuvers on the WCML: Preston - Carlisle'
  GS: '10'
  Guide: true
  Number of Gamers: 44
  Percentage of Gamers: 40%
  Ratio: 5.63
  TA: '56'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'PSC: Well Travelled'
  Description: 'Complete 20 services on the WCML: Preston - Carlisle line'
  GS: '30'
  Guide: false
  Number of Gamers: 32
  Percentage of Gamers: 29%
  Ratio: 6.6
  TA: '198'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'PSC: The Collector'
  Description: 'Complete all route tasks on WCML: Preston - Carlisle'
  GS: '30'
  Guide: true
  Number of Gamers: 22
  Percentage of Gamers: 20%
  Ratio: 7.96
  TA: '239'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'MKN: Seeing the Sights'
  Description: Drive the DB BR 425 for 42 kilometers within the speed limit
  GS: '10'
  Guide: false
  Number of Gamers: 56
  Percentage of Gamers: 93%
  Ratio: 4.3
  TA: '43'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'MKN: Mannheim Master'
  Description: 'Complete 5 scenarios on the Ludwigsbahn: Mannheim - Kaiserslautern
    line'
  GS: '30'
  Guide: false
  Number of Gamers: 18
  Percentage of Gamers: 30%
  Ratio: 7.58
  TA: '227'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'MKN: Crossed the Canal'
  Description: 'Complete 20 services on the Ludwigsbahn: Mannheim - Kaiserslautern
    line'
  GS: '30'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 18%
  Ratio: 9.7
  TA: '291'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'MKN: Completionist'
  Description: 'Complete all route tasks on the Ludwigsbahn: Mannheim - Kaiserslautern
    line'
  GS: '20'
  Guide: true
  Number of Gamers: 8
  Percentage of Gamers: 13%
  Ratio: 12.16
  TA: '243'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'MKN: Special Delivery'
  Description: Complete the "Chemical Courier" scenario
  GS: '10'
  Guide: false
  Number of Gamers: 25
  Percentage of Gamers: 42%
  Ratio: 6.43
  TA: '64'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'MITT: After a while, Crocodile'
  Description: "Drive the \xD6BB 1020 for 102.0 kilometers within the speed limit"
  GS: '20'
  Guide: false
  Number of Gamers: 11
  Percentage of Gamers: 65%
  Ratio: 7.08
  TA: '141'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'MITT: Mountain Climber'
  Description: Complete 5 scenarios on Mittenwaldbahn
  GS: '30'
  Guide: false
  Number of Gamers: 7
  Percentage of Gamers: 41%
  Ratio: 8.87
  TA: '266'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'MITT: Rumbling Success'
  Description: Complete 20 services on Mittenwaldbahn
  GS: '20'
  Guide: false
  Number of Gamers: 5
  Percentage of Gamers: 29%
  Ratio: 10.5
  TA: '210'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'MITT: Compulsive Orderliness'
  Description: Complete all route tasks on Mittenwaldbahn
  GS: '20'
  Guide: true
  Number of Gamers: 8
  Percentage of Gamers: 47%
  Ratio: 8.3
  TA: '166'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'MITT: Bumping Around'
  Description: Complete 15 coupling maneuvers on Mittenwaldbahn
  GS: '10'
  Guide: true
  Number of Gamers: 9
  Percentage of Gamers: 53%
  Ratio: 7.82
  TA: '78'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
Base Completion Time:
- 1.0
- 2.0
Base GS: 1000
Base Game Achievements:
- Achievement Name: 'TSW5: Pathfinder'
  Description: Drive any locomotive for 5 miles
  GS: '10'
  Guide: true
  Number of Gamers: 6230
  Percentage of Gamers: 35%
  Ratio: 1.69
  TA: '16'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'TSW5: Score!'
  Description: Drive any locomotive for 20 miles
  GS: '20'
  Guide: true
  Number of Gamers: 5330
  Percentage of Gamers: 30%
  Ratio: 1.83
  TA: '36'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'TSW5: Achieving Gold'
  Description: Drive any locomotive for 50 miles
  GS: '50'
  Guide: true
  Number of Gamers: 4654
  Percentage of Gamers: 26%
  Ratio: 1.96
  TA: '98'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'TSW5: Centurion'
  Description: Drive any locomotive for 100 miles
  GS: '75'
  Guide: true
  Number of Gamers: 3990
  Percentage of Gamers: 22%
  Ratio: 2.11
  TA: '158'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'TSW5: Intuition'
  Description: Drive any locomotive for 250 miles
  GS: '100'
  Guide: true
  Number of Gamers: 3081
  Percentage of Gamers: 17%
  Ratio: 2.41
  TA: '241'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'TSW5: Proclaimer'
  Description: Drive any locomotive for 500 miles
  GS: '150'
  Guide: true
  Number of Gamers: 2374
  Percentage of Gamers: 13%
  Ratio: 2.74
  TA: '411'
  Tags:
  - Offline Mode
  - Single Player
  - Cumulative +
- Achievement Name: 'TSW5: Freshman'
  Description: Complete 1 Training Module
  GS: '10'
  Guide: true
  Number of Gamers: 16203
  Percentage of Gamers: 90%
  Ratio: 1.05
  TA: '10'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Graduate'
  Description: Complete 4 Training Modules
  GS: '20'
  Guide: true
  Number of Gamers: 9225
  Percentage of Gamers: 52%
  Ratio: 1.39
  TA: '27'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: First Step'
  Description: Reach Driver Level 2
  GS: '20'
  Guide: true
  Number of Gamers: 10121
  Percentage of Gamers: 57%
  Ratio: 1.33
  TA: '26'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Artist'
  Description: Create your first reskin in the Livery Designer
  GS: '50'
  Guide: true
  Number of Gamers: 1756
  Percentage of Gamers: 10%
  Ratio: 3.19
  TA: '159'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Livery Layer Leader'
  Description: Use 500 layers in the Livery Designer
  GS: '150'
  Guide: true
  Number of Gamers: 832
  Percentage of Gamers: 5%
  Ratio: 4.63
  TA: '695'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Cunning Plan'
  Description: Create your first scenario in the Scenario Planner
  GS: '50'
  Guide: true
  Number of Gamers: 1619
  Percentage of Gamers: 9%
  Ratio: 3.32
  TA: '166'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Quality Assurance'
  Description: Complete 1 of your created scenarios
  GS: '20'
  Guide: true
  Number of Gamers: 886
  Percentage of Gamers: 5%
  Ratio: 4.49
  TA: '89'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Exhibitionist'
  Description: Complete a scenario using your own created livery
  GS: '20'
  Guide: true
  Number of Gamers: 874
  Percentage of Gamers: 5%
  Ratio: 4.52
  TA: '90'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: Taskmaster'
  Description: Complete any set of route tasks
  GS: '50'
  Guide: true
  Number of Gamers: 877
  Percentage of Gamers: 5%
  Ratio: 4.51
  TA: '225'
  Tags:
  - Offline Mode
  - Single Player
  - Collectable
- Achievement Name: 'TSW5: Trainspotting'
  Description: Capture your first photo using the Photo Mode
  GS: '10'
  Guide: true
  Number of Gamers: 2307
  Percentage of Gamers: 13%
  Ratio: 2.78
  TA: '27'
  Tags:
  - Offline Game Mode
  - Single Player
- Achievement Name: 'TSW5: First Success'
  Description: Complete your first scenario in Beginner Mode
  GS: '20'
  Guide: true
  Number of Gamers: 1736
  Percentage of Gamers: 10%
  Ratio: 3.21
  TA: '64'
  Tags:
  - Offline Mode
  - Single Player
  - Difficulty Specific
  - External Content
- Achievement Name: 'TSW5: Setting the Standard'
  Description: Complete your first scenario in Standard Mode
  GS: '75'
  Guide: true
  Number of Gamers: 1342
  Percentage of Gamers: 7%
  Ratio: 3.65
  TA: '273'
  Tags:
  - Offline Mode
  - Single Player
  - Difficulty Specific
  - External Content
- Achievement Name: 'TSW5: Top Link!'
  Description: Complete your first scenario in Expert Mode
  GS: '100'
  Guide: true
  Number of Gamers: 1245
  Percentage of Gamers: 7%
  Ratio: 3.79
  TA: '379'
  Tags:
  - Offline Mode
  - Single Player
  - Difficulty Specific
  - External Content
Base Ratio: 3.19
Base TA: 3190
Delisted: false
Developer: Dovetail Games, Rivet Games, Just Trains, Skyhook Games, TSG, ATS
Game Name: Train Sim World 5
Genres: Simulation
Install Size: 7830.0
Number of Completions: 4
Number of Gamers: 17905
Overall Completion Time:
- 1.0
- 2.0
Overall GS: 1800
Overall Ratio: 4.292777777777777
Overall TA: 7727
PDU: 0
Percentage Completed: 0.02
Publisher: Dovetail Games
Release Date: 17 September 2024
Server Closure: false
Site Rating: 3.52
Update Achievements: []
Walkthrough: false
