Add On Achievements: []
Base Completion Time:
- 19
- 20
Base GS: 1000
Base Game Achievements:
- Achievement Name: Honest Mistake
  Description: Crash 20 trains.
  GS: '20'
  Guide: false
  Number of Gamers: 126
  Percentage of Gamers: 62%
  Ratio: 1.26
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Crash Delight
  Description: Crash 50 trains.
  GS: '20'
  Guide: false
  Number of Gamers: 81
  Percentage of Gamers: 40%
  Ratio: 1.57
  TA: '31'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Train Graveyard
  Description: Crash 100 trains.
  GS: '20'
  Guide: false
  Number of Gamers: 53
  Percentage of Gamers: 26%
  Ratio: 1.95
  TA: '39'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Smooth
  Description: Play for 2 consecutive minutes without any accidents.
  GS: '20'
  Guide: false
  Number of Gamers: 196
  Percentage of Gamers: 97%
  Ratio: 1.01
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Fluid
  Description: Play for 5 consecutive minutes without any accidents.
  GS: '20'
  Guide: false
  Number of Gamers: 172
  Percentage of Gamers: 85%
  Ratio: 1.08
  TA: '21'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Free Flowing
  Description: Play for 10 consecutive minutes without any accidents.
  GS: '20'
  Guide: false
  Number of Gamers: 126
  Percentage of Gamers: 62%
  Ratio: 1.26
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Try Again
  Description: Fail a level.
  GS: '20'
  Guide: false
  Number of Gamers: 191
  Percentage of Gamers: 94%
  Ratio: 1.02
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Tough Nut
  Description: Fail a level 3 times in a row.
  GS: '20'
  Guide: false
  Number of Gamers: 136
  Percentage of Gamers: 67%
  Ratio: 1.21
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: One After Another
  Description: Clear 3 consecutive levels without returning to menu.
  GS: '20'
  Guide: false
  Number of Gamers: 139
  Percentage of Gamers: 68%
  Ratio: 1.2
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: The Law of Series
  Description: Clear 5 consecutive levels without returning to menu.
  GS: '20'
  Guide: true
  Number of Gamers: 50
  Percentage of Gamers: 25%
  Ratio: 2.01
  TA: '40'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Hot Streak
  Description: Clear 10 consecutive levels without returning to menu
  GS: '20'
  Guide: true
  Number of Gamers: 16
  Percentage of Gamers: 8%
  Ratio: 3.55
  TA: '71'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Each One Counts
  Description: Get 100 trains safely to their destination.
  GS: '20'
  Guide: false
  Number of Gamers: 139
  Percentage of Gamers: 68%
  Ratio: 1.2
  TA: '24'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Counting Sheep
  Description: Get 500 trains safely to their destination.
  GS: '20'
  Guide: false
  Number of Gamers: 62
  Percentage of Gamers: 31%
  Ratio: 1.8
  TA: '36'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Still Counting
  Description: Get 1000 trains safely to their destination.
  GS: '20'
  Guide: false
  Number of Gamers: 37
  Percentage of Gamers: 18%
  Ratio: 2.33
  TA: '46'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Second Chance
  Description: Use the heart power-up 10 times.
  GS: '20'
  Guide: false
  Number of Gamers: 90
  Percentage of Gamers: 44%
  Ratio: 1.49
  TA: '29'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Live and Let Live
  Description: Finish a level without losing a heart 5 times (when available).
  GS: '20'
  Guide: false
  Number of Gamers: 46
  Percentage of Gamers: 23%
  Ratio: 2.09
  TA: '41'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Boost
  Description: Use fast forward for 60 seconds.
  GS: '20'
  Guide: false
  Number of Gamers: 170
  Percentage of Gamers: 84%
  Ratio: 1.09
  TA: '21'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Turbo
  Description: Use fast forward for 600 seconds.
  GS: '20'
  Guide: false
  Number of Gamers: 126
  Percentage of Gamers: 62%
  Ratio: 1.26
  TA: '25'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Slow and Steady
  Description: Finish a level without using fast forward.
  GS: '20'
  Guide: false
  Number of Gamers: 163
  Percentage of Gamers: 80%
  Ratio: 1.11
  TA: '22'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Fast and Furious
  Description: Finish a level while always using fast forward.
  GS: '20'
  Guide: true
  Number of Gamers: 148
  Percentage of Gamers: 73%
  Ratio: 1.16
  TA: '23'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Perfect Level
  Description: Earn 3 stars on any map.
  GS: '20'
  Guide: false
  Number of Gamers: 200
  Percentage of Gamers: 99%
  Ratio: 1.0
  TA: '20'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: These stars...
  Description: Earn 50 stars in total.
  GS: '20'
  Guide: false
  Number of Gamers: 47
  Percentage of Gamers: 23%
  Ratio: 2.07
  TA: '41'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: '...are shining...'
  Description: Earn 100 stars in total.
  GS: '20'
  Guide: false
  Number of Gamers: 27
  Percentage of Gamers: 13%
  Ratio: 2.73
  TA: '54'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: '...in the sky'
  Description: Earn 150 stars in total.
  GS: '20'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 11%
  Ratio: 2.96
  TA: '59'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Full Clear
  Description: Collect all stars.
  GS: '40'
  Guide: false
  Number of Gamers: 17
  Percentage of Gamers: 8%
  Ratio: 3.44
  TA: '137'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: On and Off
  Description: Switch lights 50 times.
  GS: '20'
  Guide: false
  Number of Gamers: 161
  Percentage of Gamers: 79%
  Ratio: 1.12
  TA: '22'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Switching Machine
  Description: Switch lights 500 times.
  GS: '20'
  Guide: false
  Number of Gamers: 100
  Percentage of Gamers: 49%
  Ratio: 1.42
  TA: '28'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Green Wave
  Description: Have 5 green lights active at the same time for 5 seconds.
  GS: '20'
  Guide: false
  Number of Gamers: 71
  Percentage of Gamers: 35%
  Ratio: 1.68
  TA: '33'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Left and Right
  Description: Change railroad switches 100 times.
  GS: '20'
  Guide: false
  Number of Gamers: 80
  Percentage of Gamers: 39%
  Ratio: 1.58
  TA: '31'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Up and Down
  Description: Move the drawbridge 50 times.
  GS: '20'
  Guide: false
  Number of Gamers: 66
  Percentage of Gamers: 33%
  Ratio: 1.74
  TA: '34'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Sandy Wastelands
  Description: Clear all Desert levels.
  GS: '40'
  Guide: false
  Number of Gamers: 47
  Percentage of Gamers: 23%
  Ratio: 2.07
  TA: '82'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Main Storyline
- Achievement Name: Green Grass
  Description: Clear all Forest levels.
  GS: '40'
  Guide: false
  Number of Gamers: 26
  Percentage of Gamers: 13%
  Ratio: 2.78
  TA: '111'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Main Storyline
- Achievement Name: Good Cold Times
  Description: Clear all Winter levels.
  GS: '40'
  Guide: false
  Number of Gamers: 22
  Percentage of Gamers: 11%
  Ratio: 3.03
  TA: '121'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Main Storyline
- Achievement Name: After Midnight
  Description: Clear all Midnight levels.
  GS: '40'
  Guide: false
  Number of Gamers: 22
  Percentage of Gamers: 11%
  Ratio: 3.03
  TA: '121'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Main Storyline
- Achievement Name: Endless Beginnings
  Description: Play on 20 Endless maps.
  GS: '20'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 9%
  Ratio: 3.26
  TA: '65'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: A Little While
  Description: Set a time of 5 minutes on any Endless level.
  GS: '20'
  Guide: false
  Number of Gamers: 21
  Percentage of Gamers: 10%
  Ratio: 3.1
  TA: '62'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Quite Some Time
  Description: Set a time of 10 minutes on any Endless level.
  GS: '20'
  Guide: false
  Number of Gamers: 20
  Percentage of Gamers: 10%
  Ratio: 3.17
  TA: '63'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: For a Lifetime
  Description: Set a time of 15 minutes on any Endless level.
  GS: '20'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 9%
  Ratio: 3.26
  TA: '65'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
- Achievement Name: Above the Threshold
  Description: Set a time of 5 minutes on 10 Endless levels.
  GS: '20'
  Guide: false
  Number of Gamers: 18
  Percentage of Gamers: 9%
  Ratio: 3.35
  TA: '67'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Mountaineer
  Description: Sweep 10 trains with an avalanche.
  GS: '20'
  Guide: false
  Number of Gamers: 21
  Percentage of Gamers: 10%
  Ratio: 3.1
  TA: '62'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Diver
  Description: Drown 10 trains in a river.
  GS: '20'
  Guide: false
  Number of Gamers: 23
  Percentage of Gamers: 11%
  Ratio: 2.96
  TA: '59'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Tornado
  Description: Scatter 10 trains with a whirlwind.
  GS: '20'
  Guide: false
  Number of Gamers: 48
  Percentage of Gamers: 24%
  Ratio: 2.05
  TA: '41'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: From the Sky
  Description: Destroy 10 trains with a metorite.
  GS: '20'
  Guide: false
  Number of Gamers: 19
  Percentage of Gamers: 9%
  Ratio: 3.26
  TA: '65'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Lumberjack
  Description: Crash 10 trains with a fallen tree.
  GS: '20'
  Guide: false
  Number of Gamers: 22
  Percentage of Gamers: 11%
  Ratio: 3.03
  TA: '60'
  Tags:
  - Offline Mode
  - Single Player
  - Cooperative
  - Cumulative +
- Achievement Name: Duo
  Description: Clear a level with 2 or more players.
  GS: '20'
  Guide: false
  Number of Gamers: 47
  Percentage of Gamers: 23%
  Ratio: 2.07
  TA: '41'
  Tags:
  - Offline Mode
  - Cooperative
Base Ratio: 2.151
Base TA: 2151
Delisted: false
Developer: Baltoro Games
Game Name: Train Traffic Manager
Genres: Puzzle
Install Size: 4450.0
Number of Completions: 14
Number of Gamers: 203
Overall Completion Time:
- 19
- 20
Overall GS: 1000
Overall Ratio: 2.151
Overall TA: 2151
PDU: 0
Percentage Completed: 6.9
Publisher: Baltoro Games
Release Date: 24 November 2023
Server Closure: false
Site Rating: 3.55
Update Achievements: []
Walkthrough: false
